import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { AndroidConfig, type ConfigPlugin, withAndroidManifest, withDangerousMod } from '@expo/config-plugins';
import type { ExpoConfig } from 'expo/config';

/**
 * Everything that makes this an app a watch will run, and offer as its assistant.
 *
 * All of it is manifest, and all of it was verified on Wear OS 6.1 and 7 emulators by the plain
 * Gradle prototype this app replaced — see AGENTS.md. Three things carry over:
 *
 * - `uses-feature android.hardware.type.watch`, which is what makes it a watch app: the package
 *   manager and the Play Store keep it off phones, which matters here because it shares the
 *   phone app's package name.
 * - the `standalone` meta-data, so it installs and runs without the phone app.
 * - an `ASSIST` intent filter on the one activity. That is the whole assistant registration on a
 *   watch — there is no `VoiceInteractionService`, unlike the phone. Wear OS offers any app with
 *   such an activity under **Digital assistant app**, which is how Home Assistant's watch app is
 *   registered too. `VOICE_ASSIST` is there because some watches send that instead.
 *
 * Written as a plugin because `android/` is generated by prebuild: an edit made there is lost the
 * next time anyone runs it.
 */
const withWatchAssistant: ConfigPlugin = (config) =>
  withAndroidManifest(config, (manifested) => {
    const manifest = manifested.modResults.manifest;

    const features = manifest['uses-feature'] ?? [];
    if (!features.some((feature) => feature.$['android:name'] === 'android.hardware.type.watch')) {
      // `required` is what makes this a watch app rather than an app that merely likes
      // watches: a device without the feature refuses to install it, which is how the phone
      // app and this one share a package name without colliding.
      features.push({ $: { 'android:name': 'android.hardware.type.watch', 'android:required': 'true' } });
    }
    manifest['uses-feature'] = features;

    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifested.modResults);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      application,
      'com.google.android.wearable.standalone',
      'true',
      'value',
    );

    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(manifested.modResults);
    const filters = activity['intent-filter'] ?? [];
    filters.push({
      action: [
        { $: { 'android:name': 'android.intent.action.ASSIST' } },
        { $: { 'android:name': 'android.intent.action.VOICE_ASSIST' } },
      ],
      category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
    });
    activity['intent-filter'] = filters;

    return manifested;
  });

/**
 * Tells the phone app that Jarvis is on this watch.
 *
 * A phone cannot ask a watch what it has installed. What it can do is ask the Wearable Data Layer
 * which nearby devices advertise a named capability, and this is where that name is advertised —
 * the file has to be `res/values/wear.xml` with an `android_wear_capabilities` array, which is a
 * shape Google Play Services looks for by convention rather than anything Expo knows about.
 *
 * Without it the phone's settings screen would say Jarvis is not on the watch however many times
 * it had been installed, because there would be nothing to see.
 *
 * Written straight to disk because `android/` is generated, and because a string *array* is not
 * something the strings.xml helpers model. The name must match `JARVIS_ON_THE_WATCH` in
 * `mobile/modules/jarvis-watch`; `watch-link.contract.spec.ts` reads both and fails if they drift.
 */
const withWatchCapability: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    'android',
    (generated) => {
      const values = join(generated.modRequest.platformProjectRoot, 'app/src/main/res/values');
      mkdirSync(values, { recursive: true });
      writeFileSync(
        join(values, 'wear.xml'),
        `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string-array name="android_wear_capabilities">
    <item>jarvis_on_the_watch</item>
  </string-array>
</resources>
`,
      );
      return generated;
    },
  ]);

/**
 * Jarvis on the wrist.
 *
 * The same sphere as the phone app, from the same files: `hologram/` holds the drawing and the
 * voice tracking, and both apps bundle it from source. What is here is only what a watch does
 * differently — a round screen with no margins, and an assistant gesture that arrives as an
 * intent rather than through a voice interaction session.
 *
 * The package name is the phone app's on purpose. The Wearable Data Layer only connects a phone
 * app and a watch app that share one, and the ElevenLabs key is meant to reach the watch that way
 * rather than be typed on it. `uses-feature ... watch` above is what keeps the two APKs from
 * colliding on a phone.
 */
const config: ExpoConfig = {
  name: 'Jarvis',
  slug: 'hey-jarvis-wear',
  version: '0.1.0',
  orientation: 'portrait',
  userInterfaceStyle: 'dark',
  // A watch screen is OLED and mostly off. Black is not a colour choice here: it is the part of
  // the screen that costs nothing to light.
  backgroundColor: '#000000',
  // Android only. There is no watch in a browser, and Apple has no assistant to replace.
  platforms: ['android'],
  android: {
    package: 'com.ffmathy.heyjarvis',
    permissions: [
      // The conversation, once there is one. The sphere idles without it.
      'android.permission.RECORD_AUDIO',
      'android.permission.MODIFY_AUDIO_SETTINGS',
      'android.permission.INTERNET',
      'android.permission.ACCESS_NETWORK_STATE',
      'android.permission.WAKE_LOCK',
    ],
  },
};

export default withWatchCapability(withWatchAssistant(config));
