import { AndroidConfig, type ConfigPlugin, withAndroidManifest, withAndroidStyles } from '@expo/config-plugins';
import type { ExpoConfig } from 'expo/config';

/** The theme the plugin below writes, and points the app's one activity at. */
const TRANSPARENT_THEME = 'Theme.App.Transparent';

/**
 * Makes the app's window see-through, so what was on screen before it stays visible behind.
 *
 * Jarvis is an assistant: he is summoned over whatever you were doing, and a sheet you can see
 * the home screen through says that where a full screen of app does not. Sample mode is the
 * first place it shows — the hologram floating over the launcher rather than replacing it.
 *
 * A window is per activity, not per screen, and this app has one activity for all of them, so
 * every screen is drawn on a transparent window and each one paints its own background: see
 * `app.tsx`, where the root is opaque for settings and the conversation and clear for sample
 * mode. `windowIsTranslucent` is what keeps the activity behind visible rather than being
 * stopped, and it also turns the splash screen off, which suits an assistant that should appear
 * rather than launch.
 *
 * Written as a plugin because `android/` is generated by prebuild: an edit made there is lost
 * the next time anyone runs it.
 */
const withTransparentWindow: ConfigPlugin = (config) => {
  const withStyle = withAndroidStyles(config, (styled) => {
    styled.modResults = AndroidConfig.Styles.assignStylesValue(styled.modResults, {
      add: true,
      parent: { name: TRANSPARENT_THEME, parent: 'Theme.AppCompat.DayNight.NoActionBar' },
      name: 'android:windowIsTranslucent',
      value: 'true',
    });
    styled.modResults = AndroidConfig.Styles.assignStylesValue(styled.modResults, {
      add: true,
      parent: { name: TRANSPARENT_THEME, parent: 'Theme.AppCompat.DayNight.NoActionBar' },
      name: 'android:windowBackground',
      value: '@android:color/transparent',
    });
    for (const bar of ['android:statusBarColor', 'android:navigationBarColor']) {
      styled.modResults = AndroidConfig.Styles.assignStylesValue(styled.modResults, {
        add: true,
        parent: { name: TRANSPARENT_THEME, parent: 'Theme.AppCompat.DayNight.NoActionBar' },
        name: bar,
        value: '@android:color/transparent',
      });
    }
    // Show the wallpaper behind, for when there is nothing else to show.
    //
    // A translucent window reveals whatever is under it, and what that is depends on how the app
    // was opened. Summoned as the assistant it is the app you were using, which is the point.
    // Opened from the launcher it is a different task, and Android does not keep that drawn — so
    // without this there is nothing behind and the window is simply black, which is what the
    // user saw.
    styled.modResults = AndroidConfig.Styles.assignStylesValue(styled.modResults, {
      add: true,
      parent: { name: TRANSPARENT_THEME, parent: 'Theme.AppCompat.DayNight.NoActionBar' },
      name: 'android:windowShowWallpaper',
      value: 'true',
    });
    // And AppTheme's own background goes, because Expo's MainActivity sets that theme again in
    // `onCreate` — the window is created translucent from the manifest, and then an opaque
    // #05070d is painted straight over it. Every screen paints its own background (see
    // `app.tsx`), so the window does not need to.
    styled.modResults = AndroidConfig.Styles.assignStylesValue(styled.modResults, {
      add: true,
      parent: { name: 'AppTheme', parent: 'Theme.AppCompat.DayNight.NoActionBar' },
      name: 'android:windowBackground',
      value: '@android:color/transparent',
    });
    return styled;
  });

  return withAndroidManifest(withStyle, (manifested) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(manifested.modResults);
    activity.$['android:theme'] = `@style/${TRANSPARENT_THEME}`;
    return manifested;
  });
};

/**
 * The Android app Jarvis answers from.
 *
 * There is no `plugins` entry for the assistant registration, on purpose. The
 * `modules/jarvis-assistant` local module is a Gradle library project, so the
 * manifest under `modules/jarvis-assistant/android/src/main` is merged into the
 * app's own during the build — the same way `expo-file-system` declares its
 * file provider. Everything the system needs in order to offer Jarvis in the
 * assistant picker is therefore declared next to the Kotlin that implements it,
 * rather than in a config plugin patching a generated file.
 */
const config: ExpoConfig = {
  name: 'Jarvis',
  slug: 'hey-jarvis',
  version: '0.1.0',
  orientation: 'portrait',
  // How the voice interaction session hands control back to the app. The
  // assistant is summoned from outside the app, so there has to be a URL that
  // reaches it: `heyjarvis://assist`.
  scheme: 'heyjarvis',
  userInterfaceStyle: 'dark',
  backgroundColor: '#05070d',
  // No iOS target. Apple has no equivalent of the assistant role — Siri cannot
  // be replaced — so it would ship something that cannot do the one thing this
  // app exists for.
  //
  // Web is here for a smaller reason, but a real one: the conversation is the
  // whole app apart from the assist gesture, and it runs in a browser on the
  // same `ConversationProvider` over the browser's own WebRTC. Taking over the
  // assist gesture stays Android's, and the app says so when it is on web rather
  // than leaving a button that cannot work.
  platforms: ['android', 'web'],
  // GitHub Pages serves a project site from a folder, not the root, so the web
  // build has to know it is under one or every asset it asks for 404s. Set only
  // when publishing there — `expo serve`, which the browser tests use, serves at
  // the root and a prefix would break it.
  experiments: process.env.PAGES_BASE_URL ? { baseUrl: process.env.PAGES_BASE_URL } : undefined,
  web: {
    bundler: 'metro',
    output: 'single',
  },
  android: {
    package: 'com.ffmathy.heyjarvis',
    permissions: [
      // The conversation itself.
      'android.permission.RECORD_AUDIO',
      'android.permission.MODIFY_AUDIO_SETTINGS',
      // WebRTC needs to know whether it is on wifi or cellular to pick a
      // candidate, and holds a wake lock so a sentence is not cut off by the
      // screen going to sleep.
      'android.permission.ACCESS_NETWORK_STATE',
      'android.permission.INTERNET',
      'android.permission.WAKE_LOCK',
      // Assistants are routinely summoned through a headset button, and the
      // audio has to follow the headset when they are.
      'android.permission.BLUETOOTH_CONNECT',
    ],
    // `@livekit/react-native` declares CAMERA in its own manifest because the
    // same module also does video calls. Jarvis never opens a camera, and a
    // permission nobody uses is a permission nobody can audit, so it is merged
    // straight back out again.
    blockedPermissions: ['android.permission.CAMERA'],
  },
  plugins: [
    'expo-dev-client',
    // Applies expo-secure-store's Auto Backup and data-extraction rules, which
    // keep its storage — where the ElevenLabs API key lives — out of cloud backups
    // and device-to-device transfers. Without them the encrypted entry is backed
    // up anyway: undecryptable elsewhere, since the keystore key does not travel,
    // but copied off the phone all the same.
    'expo-secure-store',
    // Writes the meta-data that LiveKit's own lifecycle listener reads at
    // startup to pick an audio mode. Without it the native audio session is set
    // up for media playback rather than a call: the microphone routes to the
    // earpiece, and Jarvis hears his own voice back.
    ['@livekit/react-native-expo-plugin', { android: { audioType: 'communication' } }],
  ],
};

export default withTransparentWindow(config);
