#!/usr/bin/env bun
/**
 * Custom build script that uses @mastra/deployer programmatically to build
 * the Mastra application with UI/Studio included (dev mode).
 *
 * This script replicates what `mastra build` does but works around the nested
 * dependency issue by using the deployer API directly.
 */

import { cpSync, existsSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

// Paths
const projectRoot = resolve(import.meta.dir, '..');
const mastraDir = resolve(projectRoot, 'mastra');
const outputDir = resolve(projectRoot, '.mastra-build');
const publicDir = resolve(mastraDir, 'public');

console.log('🚀 Building Mastra application with UI...');
console.log(`   Project: ${projectRoot}`);
console.log(`   Mastra:  ${mastraDir}`);
console.log(`   Output:  ${outputDir}`);

// Clean output directory
if (existsSync(outputDir)) {
  console.log('\n🧹 Cleaning output directory...');
  rmSync(outputDir, { recursive: true, force: true });
}
mkdirSync(outputDir, { recursive: true });

try {
  // Step 1: Create the server entry point that serves the UI
  console.log('\n📝 Creating server entry point...');

  const serverContent = `/**
 * Production server entry point with Mastra UI/Studio
 * Generated by build-with-ui.ts
 */

import { serve } from 'bun';
import app, { logTokenUsageSummary, mastra } from './index.ts';

const port = Number.parseInt(process.env.MASTRA_SERVER_PORT || '4111', 10);
const host = process.env.HOST || '0.0.0.0';

// Log token usage statistics on startup
await logTokenUsageSummary();

console.log(\`🚀 Starting Mastra server with UI on $\{host}:$\{port}...\`);

// Start the Bun server with the Hono app
serve({
  port,
  hostname: host,
  fetch: app.fetch,
});

console.log(\`✅ Mastra server running at http://$\{host}:$\{port}\`);
console.log(\`📊 OpenAPI docs: http://$\{host}:$\{port}/openapi.json\`);
console.log(\`🎨 Mastra Studio: http://$\{host}:$\{port}/\`);
console.log(\`🏥 Health check: http://$\{host}:$\{port}/health\`);
`;

  await writeFile(resolve(outputDir, 'server.mjs'), serverContent);
  console.log('   ✓ Created server.mjs');

  // Step 2: Copy the mastra index and all TypeScript files
  console.log('\n📦 Copying application files...');

  // Copy index.ts (Bun will handle TypeScript natively)
  cpSync(resolve(mastraDir, 'index.ts'), resolve(outputDir, 'index.ts'), { recursive: true });
  console.log('   ✓ Copied index.ts');

  // Copy all other necessary directories
  const dirsToCopy = ['storage', 'utils', 'verticals'];
  for (const dir of dirsToCopy) {
    const srcDir = resolve(mastraDir, dir);
    if (existsSync(srcDir)) {
      cpSync(srcDir, resolve(outputDir, dir), { recursive: true });
      console.log(`   ✓ Copied ${dir}/`);
    }
  }

  // Step 3: Copy public directory (static files for UI)
  if (existsSync(publicDir)) {
    console.log('\n🎨 Copying UI assets from public/...');
    cpSync(publicDir, resolve(outputDir, 'public'), { recursive: true });
    const files = readdirSync(resolve(outputDir, 'public'));
    console.log(`   ✓ Copied ${files.length} files`);
  } else {
    console.log('\n⚠️  No public/ directory found - UI assets may be missing');
  }

  // Step 4: Create package.json for the output
  console.log('\n📝 Creating package.json...');

  const packageJson = {
    name: 'hey-jarvis-mastra-server',
    version: '1.0.0',
    type: 'module',
    main: 'server.mjs',
    dependencies: {
      '@elevenlabs/elevenlabs-js': '^2.27.0',
      '@mastra/core': '1.0.0-beta.10',
      '@mastra/hono': '0.0.2-beta.3',
      '@mastra/libsql': '1.0.0-beta.7',
      '@mastra/loggers': '1.0.0-beta.3',
      '@mastra/mcp': '1.0.0-beta.6',
      '@mastra/memory': '1.0.0-beta.4',
      '@mastra/observability': '1.0.0-beta.4',
      '@mastra/server': '1.0.0-beta.10',
      twilio: '^5.10.7',
      'node-cron': '^4.2.1',
      express: '^5.2.1',
      'express-jwt': '^8.5.1',
      jsonwebtoken: '^9.0.3',
      googleapis: '^166.0.0',
      octokit: '^5.0.5',
      fkill: '^10.0.1',
      open: '^11.0.0',
      geolib: '^3.3.4',
      hono: '^4.10.8',
      zod: '^3.25.76',
    },
  };

  await writeFile(resolve(outputDir, 'package.json'), JSON.stringify(packageJson, null, 2));
  console.log('   ✓ Created package.json');

  console.log(`\n✅ Build complete!`);
  console.log(`   Output: ${outputDir}`);
  console.log(`   Entry:  ${outputDir}/server.mjs`);
  console.log(`\nNext: Run 'bun build --compile' on the output`);
} catch (error) {
  console.error('❌ Build failed:', error);
  process.exit(1);
}
