import { useEffect, useMemo, useRef, useState } from 'react';
import type { JarvisVoice, UseJarvisVoice } from '../../src/platform-contracts';

/**
 * A recorded Jarvis, for looking at the hologram where no conversation can run.
 *
 * `.scripts/verify-hologram-on-emulator.sh` bundles the app with this module in
 * place of `src/jarvis-voice.ts` (see `metro.config.js`). It replays a spoken
 * line — synthesised, then analysed into the two readings the SDK's web build gives:
 * an RMS volume and a 1024-bin byte spectrum every 40 ms — in a loop that opens
 * with silence, so one run shows the hologram idle and then speaking.
 *
 * Never part of a normal build: nothing imports it, and the recording it reads
 * is generated by the script and not committed.
 */

interface Recording {
  intervalMs: number;
  frames: { volume: number; spectrum: string }[];
}

/** Silence before each replay of the line, so idle and speaking both get seen. */
const SILENCE_MS = 6000;

function isRecording(value: unknown): value is Recording {
  return (
    typeof value === 'object' &&
    value !== null &&
    'intervalMs' in value &&
    typeof value.intervalMs === 'number' &&
    'frames' in value &&
    Array.isArray(value.frames) &&
    value.frames.every(
      (frame: unknown) =>
        typeof frame === 'object' &&
        frame !== null &&
        'volume' in frame &&
        typeof frame.volume === 'number' &&
        'spectrum' in frame &&
        typeof frame.spectrum === 'string',
    )
  );
}

// A plain require, so typechecking does not need the generated file to exist.
const loadedRecording: unknown = require('./recording/jarvis-voice.json');
if (!isRecording(loadedRecording)) {
  throw new Error('recording/jarvis-voice.json is not a recording — regenerate it with verify-hologram-on-emulator.sh');
}
const recording = loadedRecording;

const EMPTY = new Uint8Array(0);

/** Base64 to bytes without relying on `atob`, which not every JS engine the app runs on provides. */
function decodeBase64(text: string): Uint8Array {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const clean = text.replace(/=+$/, '');
  const bytes = new Uint8Array(Math.floor((clean.length * 3) / 4));
  let buffer = 0;
  let bits = 0;
  let index = 0;
  for (const character of clean) {
    buffer = (buffer << 6) | alphabet.indexOf(character);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes[index++] = (buffer >> bits) & 0xff;
    }
  }
  return bytes;
}

export const useJarvisVoice: UseJarvisVoice = (): JarvisVoice => {
  const frames = useMemo(
    () => recording.frames.map((frame) => ({ volume: frame.volume, spectrum: decodeBase64(frame.spectrum) })),
    [],
  );
  const startedAt = useRef(Date.now());
  const speechMs = frames.length * recording.intervalMs;

  // Stable readers, so the hologram does not restart its polling on every render.
  const current = useMemo(() => {
    return () => {
      const position = (Date.now() - startedAt.current) % (SILENCE_MS + speechMs);
      if (position < SILENCE_MS) return undefined;
      return frames[Math.floor((position - SILENCE_MS) / recording.intervalMs)];
    };
  }, [frames, speechMs]);

  const [speaking, setSpeaking] = useState(false);
  useEffect(() => {
    const timer = setInterval(() => setSpeaking(current() !== undefined), 100);
    return () => clearInterval(timer);
  }, [current]);

  // Stable across `speaking` changes, as in src/jarvis-voice.ts.
  const readers = useMemo(
    () => ({
      getVolume: () => current()?.volume ?? 0,
      getSpectrum: () => current()?.spectrum ?? EMPTY,
    }),
    [current],
  );

  return { listening: true, speaking, ...readers };
};
