// Main verticals exports
export * from './calendar/index.js';
export * from './coding/index.js';
export * from './commute/index.js';
export * from './cooking/index.js';
export * from './email/index.js';
export * from './human-in-the-loop/index.js';
export * from './internet-of-things/index.js';
export * from './notification/index.js';
export * from './shopping/index.js';
export * from './synapse/index.js';
export * from './todo-list/index.js';
export * from './weather/index.js';
export * from './web-research/index.js';
