name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: npm run build