name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test in dev container
        uses: devcontainers/ci@v0.3
        env:
          # Environment variables for Home Assistant Voice firmware build
          ELEVENLABS_AGENT_ID: "dummy-agent-id-for-ci"
          ELEVENLABS_API_KEY: "dummy-api-key-for-ci"
          WIFI_SSID: "dummy-wifi-ssid-for-ci"
          WIFI_PASSWORD: "dummy-wifi-password-for-ci"
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainer
          push: never
          runCmd: npm run build