name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy in dev container
        uses: devcontainers/ci@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          REGISTRY: ghcr.io
          IMAGE_OWNER: ${{ env.REPO_OWNER_LC }}
        with:
          imageName: ghcr.io/${{ env.REPO_OWNER_LC }}/devcontainer
          cacheFrom: ghcr.io/${{ env.REPO_OWNER_LC }}/devcontainer
          push: always
          runCmd: npm run deploy